-- MySQL Script generated by MySQL Workbench
-- Mon Oct 31 23:19:36 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `idUser` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `age` INT NULL,
  PRIMARY KEY (`idUser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Post` (
  `idPost` INT NOT NULL,
  `title` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  `author` VARCHAR(45) NULL,
  `content` VARCHAR(45) NULL,
  `User_idUser` INT NOT NULL,
  PRIMARY KEY (`idPost`),
  INDEX `fk_Post_User_idx` (`User_idUser` ASC) VISIBLE,
  CONSTRAINT `fk_Post_User`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `mydb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tags` (
  `idTags` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`idTags`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Comments` (
  `idComments` INT NOT NULL,
  `comment` VARCHAR(45) NULL,
  PRIMARY KEY (`idComments`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Post_Comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Post_Comment` (
  `idPost_Comment` INT NOT NULL,
  `Post_idPost` INT NOT NULL,
  `Comments_idComments` INT NOT NULL,
  PRIMARY KEY (`idPost_Comment`),
  INDEX `fk_Post_Comment_Post1_idx` (`Post_idPost` ASC) VISIBLE,
  INDEX `fk_Post_Comment_Comments1_idx` (`Comments_idComments` ASC) VISIBLE,
  CONSTRAINT `fk_Post_Comment_Post1`
    FOREIGN KEY (`Post_idPost`)
    REFERENCES `mydb`.`Post` (`idPost`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Post_Comment_Comments1`
    FOREIGN KEY (`Comments_idComments`)
    REFERENCES `mydb`.`Comments` (`idComments`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Post_Tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Post_Tags` (
  `idPost_Tags` INT NOT NULL,
  `Tags_idTags` INT NOT NULL,
  `Post_idPost` INT NOT NULL,
  PRIMARY KEY (`idPost_Tags`),
  INDEX `fk_Post_Tags_Tags1_idx` (`Tags_idTags` ASC) VISIBLE,
  INDEX `fk_Post_Tags_Post1_idx` (`Post_idPost` ASC) VISIBLE,
  CONSTRAINT `fk_Post_Tags_Tags1`
    FOREIGN KEY (`Tags_idTags`)
    REFERENCES `mydb`.`Tags` (`idTags`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Post_Tags_Post1`
    FOREIGN KEY (`Post_idPost`)
    REFERENCES `mydb`.`Post` (`idPost`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
